---
- name: Update Security AlmaLinux 9
  hosts: rhel_servers
  become: yes
  tasks:
    - name: Install security and bugfix patches
      dnf:
        name: '*'
        security: yes
        bugfix: yes
        state: latest
