---
- name: Update AlmaLinux 9
  hosts: rhel_servers
  become: yes
  tasks:
    - name: Update the package repository
      dnf:
        name: '*'
        state: latest

    - name: Clean up unused packages
      dnf:
        autoremove: yes
