---
- name: Reboot AlmaLinux 9 server
  hosts: almalinux-9.x_servers
  become: yes

  tasks:
  - name: Reboot the server
    ansible.builtin.reboot: 
      reboot_timeout: 300  # Optional: Set a timeout for the reboot (in seconds) 
