---
- name: Daily Linux Security Updates ONLY
  hosts: linux_servers
  become: yes
  tasks:
    - name: RHEL/AlmaLinux - Install Security Updates
      ansible.builtin.dnf:
        name: '*'
        security: yes
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Debian/Ubuntu - Ensure unattended-upgrades is installed
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Debian/Ubuntu - Run Security Updates via unattended-upgrades
      ansible.builtin.command: unattended-upgrade -d
      register: ubuntu_security
      changed_when: "'Packages that will be upgraded' in ubuntu_security.stdout"
      when: ansible_os_family == "Debian"
