---
- hosts: all
  become: true  # Ensure that the tasks are run with elevated privileges
  roles:
    - role: devsec.hardening.os_hardening  # Specify the role correctly
  vars:
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding.
      net.ipv4.ip_forward: 1
