---
- name: Update Proxmox Server
  hosts: proxmox_servers
  become: yes
  gather_facts: no # Mempercepat eksekusi

  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Simulasi dist-upgrade untuk mencari paket spesifik Security
      ansible.builtin.shell: >
        apt-get -s dist-upgrade | awk '/^Inst/ && /security/ {print $2}'
      register: security_packages
      changed_when: false

    - name: Log paket security yang terdeteksi ke Semaphore
      ansible.builtin.debug:
        msg: "Paket security yang akan di-install: {{ security_packages.stdout_lines | join(', ') }}"
      when: security_packages.stdout_lines | length > 0

    - name: Eksekusi instalasi Security Updates
      ansible.builtin.apt:
        name: "{{ security_packages.stdout_lines }}"
        state: latest
        only_upgrade: yes
      when: security_packages.stdout_lines | length > 0
      register: apt_result

    - name: Cek flag system reboot
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Tampilkan peringatan jika reboot dibutuhkan
      ansible.builtin.debug:
        msg: "⚠️ PENTING: Node Proxmox ini membutuhkan REBOOT untuk menerapkan update (misal: libc atau kernel update)."
      when: reboot_required.stat.exists
